version: "3"
services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.jax
    #ports:
    #  - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MTA_SERVER_HOST=127.0.0.1
      - MTA_SERVER_PORT=22005
      - MTA_SERVER_ADMIN_USERNAME=Chainik
      - MTA_SERVER_ADMIN_PASSWORD=123456
    volumes:
      - ./:/app
    privileged: true
    ipc: host
    stop_signal: SIGKILL
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
